version: '3.4'
services:
  prometheus:    
    image: prom/prometheus:v2.22.0
    hostname: prometheus
    env_file: .env
    container_name: prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      #- '--web.external-url=${PROMETHEUS_HOST}'
      #- '--web.route-prefix="/"'
      - '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/etc/prometheus/console_libraries'
      #- '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=365d'
      - '--web.enable-admin-api'
    env_file: .env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules:/alertmanager/alert.rules
      - prometheus-data:/prometheus
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST}`)
        - traefik.http.routers.prometheus.tls.certresolver=lets-encrypt
        - traefik.http.services.prometheus.loadbalancer.server.port=9090
        - traefik.http.routers.prometheus.middlewares=security-protocol-pw@file
    expose: 
      - 9090
    networks:
      - traefik
      - prometheus
    restart: unless-stopped
  alertmanager:
    hostname: alertmanager
    image: prom/alertmanager
    env_file: .env
    container_name: alertmanager
    command: 
      - '--config.file=/alertmanager/alertmanager.yml'
    restart: always
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.alertmanager.rule=Host(`${ALERTMANAGER_HOST}`)
        - traefik.http.routers.alertmanager.tls.certresolver=lets-encrypt
        - traefik.http.services.alertmanager.loadbalancer.server.port=9093
        - traefik.http.routers.alertmanager.middlewares=security-protocol-pw@file
    expose:
      - 9093
    networks:
      - traefik
      - prometheus
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
  cadvisor: 
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    env_file: .env
    hostname: cadvisor
    expose: 
      - 8080
    labels: 
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.cadvisor.rule=Host(`${CADVISOR_HOST}`)
      - traefik.http.routers.cadvisor.tls.certresolver=lets-encrypt
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    #depends_on: 
    #    - redis
    networks: 
      - traefik
      - prometheus
    restart: unless-stopped
  grafana: 
    image: grafana/grafana # add version
    container_name: grafana
    env_file: .env
    hostname: grafana
    user: "${PUID}:${GUID}"
    command: 
      - '--config=/usr/share/grafana/conf/custom.ini'
    volumes: 
      - grafana-data:/var/lib/grafana
      - ./grafana/custom.ini:/usr/share/grafana/conf/custom.ini
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      
    labels: 
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.grafana.rule=Host(`$GRAFANA_HOST`)
      - traefik.http.routers.grafana.tls.certresolver=lets-encrypt
      - traefik.http.routers.grafana.middlewares=security-protocol@file
    expose: 
      - 3000
    networks: 
      - traefik
      - prometheus
    restart: unless-stopped
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    env_file: .env
    command:
      - '--config.file=/config/blackbox.yml'
    volumes:
      - "./blackbox:/config"
    dns: 1.1.1.1
    expose: 
      - 9115
    networks:
      - prometheus
    restart: unless-stopped
  
  # https://github.com/prometheus-msteams/prometheus-msteams
  prometheus-msteams:
    hostname: prometheus-msteams
    image: quay.io/prometheusmsteams/prometheus-msteams
    container_name: prometheus-msteams
    env_file: .env
    expose: 
      - 2000
    networks: 
      - prometheus
    restart: unless-stopped


volumes: 
  prometheus-data: {}
  grafana-data: {}
networks:
  prometheus:
    name: prometheus  
  traefik:
    external: true 
    name: traefik
