version: '3.5'
services: 
  xxx:
    image: 
    env_file: .env
    container_name: 
    hostname: ${XXX_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.xxx.rule=Host(`${XXX_HOSTNAME}.${MAIN_DOMAIN}`)
      - traefik.http.routers.xxx.tls.certresolver=lets-encrypt
      - traefik.http.routers.xxx.entrypoints=web-secure
      - traefik.http.routers.xxx.middlewares=security-protocol@file
      #- traefik.http.services.xxx.loadbalancer.server.port=
      #- traefik.http.routers.xxx.middlewares=basic-auth@file
      # Enable Auto-Updates (Watchtower)
      #- com.centurylinklabs.watchtower.enable=true
      # Enable flame dashboard link
      - flame.type=application # "app" works too
      - flame.name=
      - flame.url=https://${XXX_HOSTNAME}.${MAIN_DOMAIN}
      #- flame.icon=icon-name # Optional, default is "docker"
    volumes:  
      - ${XXX_CONFIG}:/config
    networks:
      - traefik
    expose:
      - 
    restart: unless-stopped
  


networks:
  traefik:
    external: true
    name: traefik  
    
