version: '3.5'
services: 
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    env_file: .env
    container_name: unifi-controller
    hostname: unifi-controller
    labels:
      - traefik.enable=true
      - traefik.http.routers.unifi-controller.rule=Host(`${UNIFI_HOSTNAME}.${MAIN_DOMAIN}`)
      - traefik.http.routers.unifi-controller.tls.certresolver=lets-encrypt
      - traefik.http.routers.unifi-controller.entrypoints=web-secure
      #- traefik.http.routers.unifi-controller.middlewares=basic-auth@file
      # Enable Auto-Updates (Watchtower)
      #- com.centurylinklabs.watchtower.enable=true
    volumes:  
      - ${UNIFI_CONFIG}:/config
    networks:
      - traefik
    expose:
      # Unifi web admin port
      - 8443
      # TODO Check which ports comes behind the proxy
    ports:
      # Unifi STUN port
      - 3478:3478/udp               
      # Required for AP discovery                
      - 10001:10001/udp
      # Required for device communication
      - 8080:8080
      # Required for Make controller discoverable on L2 network option
      - 1900:1900/udp # optional
      # Unifi guest portal HTTPS redirect port
      - 8843:8843 # optional
      # Unifi guest portal HTTP redirect port
      - 8880:8880 # optional
      # For mobile throughput test
      - 6789:6789 # optional
      # Remote syslog port
      - 5514:5514/udp # optional
    restart: unless-stopped
  


networks:
  traefik:
    external: true
    #name: traefik   #TESTING
    
